spring.application.name=WebVideoQC

server.port=8081
debug=true

webvideoqc.ffprobe.binary=C:/ffmpeg/bin/ffprobe.exe
webvideoqc.ffprobe.timeout-seconds=1800
webvideoqc.ffmpeg.binary=C:/ffmpeg/bin/ffmpeg.exe