spring.application.name=WebVideoQC
spring.web.error.include-message=always
spring.profiles.active=prod
logging.level.org.springframework.web=TRACE
server.port=8081
debug=false
# Leave binaries unchanged if you have ffmpeg & ffprobe added in PATH
# Or use absolute:/paths/to/these/binaries
webvideoqc.ffprobe.binary=ffprobe
webvideoqc.ffprobe.timeout-seconds=1800
webvideoqc.ffmpeg.binary=ffmpeg
# Enter the absolute path to your work directory
webvideoqc.user.workdir=C:/Users/_redfox/Desktop
